name: Generate publications

on:
 page_build:
 schedule:
  - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: generate-sitemap
      uses: cicirello/generate-sitemap@v1.10.1

      # 安装依赖项
    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip install pandas openpyxl gspread

    # 执行脚本
    - name: Run publication generator script
      run: | 
        python publication_generator/pubGen.py
      env:
        GS_PRIVATE_KEY_ID: ${{ secrets.GS_PRIVATE_KEY_ID }}
        GS_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}

    # 提交并推送更新的文件
    - name: Commit and push changes
      run: |
        git config --global user.name "Zhu Deng"
        git config --global user.email "zhudeng94@gmail.com"
        git add sitemap.xml
        git add _pages/includes/pub_list.md
        git add _pages/includes/pub_selected.md
        git commit -m "Update publication list"
        git push origin main --force
